services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=ecom
      - POSTGRES_PASSWORD=ecom
      - POSTGRES_DB=ecom
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres:
